matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - pip install -r ${PWD}/python_package/requirements.txt
        - pip install flake8
        - pip install codecov
        - pip install pytest-cov
      script:
        - flake8 --show-source ${PWD}/python-package
        - py.test --cov=${PWD}/python-package ${PWD}/tests/python
      after_success:
        - codecov
