matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - pip install -r ./python-package/requirements.txt
        - pip install flake8
        - pip install codecov
        - pip install pytest-cov
      script:
        - flake8 --show-source ./python-package/
        - py.test --cov=./python-package/ ./tests/python/
      after_success:
        - codecov
